---
domains:
- "eds-1-10.streamx.awsmdb.com"
- "eds-1-14.streamx.awsmdb.com"
- "test-project.streamx.awsmdb.com"
- "test-project-2.streamx.awsmdb.com"
- "test-project-3.streamx.awsmdb.com"
global: {}
clusters:
  edge-us-east:
    enabled: true
    overlay: {}
  processing-eu-central:
    enabled: true
    overlay: {}
