---
domains:
- "eds-1-1.streamx.awsmdb.com"
- "eds-1-3.streamx.awsmdb.com"
- "eds-1-4.streamx.awsmdb.com"
- "eds-wtf.streamx.awsmdb.com"
- "eds-wtf-3.streamx.awsmdb.com"
- "eds-wtf-6.streamx.awsmdb.com"
- "eds-wtf-7.streamx.awsmdb.com"
global: {}
clusters:
  edge-us-east:
    enabled: true
    overlay: {}
  processing-eu-central:
    enabled: true
    overlay: {}
