---
domains:
- "eds-1-10.streamx.awsmdb.com"
- "eds-1-11.streamx.awsmdb.com"
- "eds-1-12.streamx.awsmdb.com"
global: {}
clusters:
  edge-us-east:
    enabled: true
    overlay: {}
  processing-eu-central:
    enabled: true
    overlay: {}
